---
title: "Teaching"
---

I am currently the project coordinator for the Cal Poly Slo Halter Ranch Conservation Scholars (HARCS) program. This is our inaugural year, and we have placed seven students in summer conservation and stewardship internships with our conservation partners. In preparation, I led those students in a quarter long seminar focused on developing conservation oriented skills such as GIS as well as understanding the fundamentals of conservation and ecology through field based activities. See the HARCS page of this webisite for more information and photos from the field. 

---


Throughout my graduate career I served as a teaching assistant for courses in botany, ecology, and evolution. I have experience leading lab sections, teaching plant identification, and guiding students through field work. I will be the instructor of record for the new semester version of Plant Diversity and Ecology this Fall semester at Cal Poly and am designing new material to fit the longer schedule. 

**UC Davis**

- Angiosperm Systematics (PLS/PLB 127) 30 students — Spring 2024
- California Floristics (PLB 102) 30 students — Spring 2021, 2022, 2023
- Evolution of the Human Life Cycle (ANT 15) 20 students — Fall 2023
- Environmental Plants (ENH 06) 20 students — Fall 2021

**Cal Poly, San Luis Obispo**

- Conservation Ecology Seminar (BIO 472) 6 student — Spring 2026
- Introductory Botany Lab (BOT 121L) 24 students — Fall 2018, 2019
- Plant Diversity and Ecology Lab (BIO 114L) 20 students — Winter 2019, 2020, Spring 2020

**UC Santa Cruz**

- Systematic Botany of Flowering Plants Lab (BIOE 117L) 25 students — Winter 2017

